name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
     - master

env:
  REGISTRY: "registry.windfarms.ru"
  IMAGE_NAME: "windfarms-backend"
  CONTAINER_NAME: "windfarms-backend"
  LOGS_PATH: "/root/windfarms-backend/api/logs/prod"


jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Set up Go 1.15.6
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.6

    - name: Test
      run: go test ./...
  
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: registry.windfarms.ru
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
   runs-on: ubuntu-latest
   if: github.event_name == 'push'
   needs: build_and_push

   steps:
    - name: Deploy to Zomro vps via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: IMAGE_NAME, REGISTRY, GITHUB_SHA, CONTAINER_NAME
        script: |
            # Login into Registry
            echo ${{ secrets.REGISTRY_PASSWORD }} | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin $(echo $REGISTRY)
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            # Run a new container from a new image
            docker run -v $(echo $LOGS_PATH):/logs -d \
            --restart always \
            --publish 8002:8002 \
            --name $(echo $CONTAINER_NAME) \
            --link=windfarms-db:db \
            -e DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            -e DB_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

